step_size: 0.01 # Try with gdx (0.5), geomatch (0.05) and our (0.02).
learning_rate: 0.5 # Try with a lower LR like 0.1 and 0.01 
contact_threshold: 0.005
num_object_pts: 2048
hmodel_type: "gcs" # Options: "gcs" (our hand model) or "gdx" (gendexgrasp). Can try both to see which gives best results